const ADD_PRODUCT = 'ADD_PRODUCT'
const CHARGE_VENDING_MONEY = 'CHARGE_MONEY'
const PURCHASE_PRODUCT = 'PURCHASE_PRODUCT'
const RETURN_COIN = 'RETURN_COIN'

export { ADD_PRODUCT, CHARGE_VENDING_MONEY, PURCHASE_PRODUCT, RETURN_COIN }
